export const SITE = {
  website: "https://zzzzswh.github.io/",
  author: "zzzzswh",
  profile: "https://github.com/zzzzswh",
  desc: "A blog about geophysics, seismic waves, AI, and scientific visualization. 一个关于地球物理、地震波、AI与科学可视化的博客。",
  title: "zzzzswh's Geophysics Blog",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  postPerArchive: 10,
  scheduledPostMargin: 15 * 60 * 1000,
  genDescriptionMaxLines: 30,
  genDescriptionCount: 200,
  showArchives: true,
  showBackButton: false,
  showPageDesc: false,
  editPost: {
    enabled: false,
    text: "Suggest Changes",
    url: "https://github.com/zzzzswh/zzzzswh.github.io/edit/main/",
  },
  dynamicOgImage: true,
  lang: "en",
  langOg: "en_US",
  timezone: "Asia/Shanghai",  // 改成你所在的时区
  wontonCommentUrl: "",
} as const;